---
language: python
python: "3.6"

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install -r requirements.txt

script:
  - molecule test -s aws

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
