---
- name: Config Apache logs
  template:
    src: apache-logs.conf
    dest: /etc/apache2/conf-available/{{ item.conf }}
    owner: root
    group: root
    mode: 0644
- name: Enable new config
  file:
    src: ../conf-available/{{ item.conf }}
    dest: /etc/apache2/conf-enabled/{{ item.conf }}
    owner: root
    group: root
    state: link
  notify: Restart Apache 2
