---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: jenkins
    box: codeyourinfra/jenkins
    instance_interfaces:
      - auto_config: true
        ip: 192.168.33.10
        network_name: private_network
        type: static
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../tests
  lint:
    name: flake8
